[package]
name = "cube3d"
description = "A GUI-based 3D cube rotation demo"
repository = "https://github.com/drewwalton19216801/cube3d"
readme = "README.md"
version = "0.5.5"
edition = "2021"
license = "MIT"
authors = ["Drew Walton <drewwalton19216801@gmail.com>"]

[dependencies]
csgrs = "0.16.0"
druid = "0.8.3"
